sudo: false
language: elixir
elixir:
  - 1.4
  - 1.5
  - 1.6
script:
  - mix test
  - ./test/smoke_test.sh
  - ./test/check_formatted.sh
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report

